source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'iOS-PicPay-Teste' do
use_frameworks!
    pod 'SDWebImage'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'GoogleSignIn'
end
